---
- hosts: proxy
  sudo: yes

  vars:
    http_port: 80
    domain: test.mageiacreaciones.com
    reverse_proxy_ip: 192.168.1.62
  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2

    - name: Create log folder
      file:
        path: /var/log/httpd
        state: directory
        owner: www-data
        group: www-data
        mode: 666

    - name: enable apache modules
      sudo: yes
      apache2_module: name={{ item }} state=present
      notify:
        - restart apache2
      loop:
         - proxy
         - proxy
         - proxy_balancer
         - proxy_http
         - remoteip
         - rewrite
         - ssl

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: create virtual host file
      template:
        src: "{{ domain }}.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.conf"

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/{{ domain }}.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
