- name: Create user
  hosts: all
  remote_user: jvbm301
  tasks:
    - name: Create .ssh folder
      file:
        path: ~jvbm301/.ssh
        state: directory
        owner: jvbm301
        group: jvbm301
        mode: 0700
    - name: Upload SSH key
      copy:
        src: /Users/jaimevalero/.ssh/id_rsa_kvm.pub
        dest: ~jvbm301/.ssh/id_rsa
        owner: jvbm301
        group: jvbm301
        mode: 0700
